src/__init__.py
__author__ = 'mktlr'

src/app.py
import os
from flask import Flask, render_template
from src.common.database import Database

__author__ = 'mktlr'


app = Flask(__name__)
app.config.from_object('config')
app.secret_key = os.environ.get('SECRET_KEY')


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.html')


from src.models.users.views import user_blueprint
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import store_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, url_for
from werkzeug.utils import redirect

import src.models.users.decorators as user_decorators
from src.models.alerts.alert import Alert
from src.models.items.item import Item

__author__ = 'mktlr'


alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()

    # What happens if it's a GET request
    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))
    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    Alert.find_by_id(alert_id).send_email_if_price_reached()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/items/views.py
from flask import Blueprint

__author__ = 'mktlr'


item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/item/<string:name>')
def item_page(name):
    pass

src/models/stores/views.py
import json

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

import src.models.users.decorators as user_decorators
from src.models.stores.store import Store

__author__ = 'mktlr'


store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/new_store.html')

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

import src.models.users.decorators as user_decorators
import src.models.users.errors as UserErrors
from src.models.users.user import User

__author__ = 'mktlr'


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        # Check Login is valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.html")


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        # Check Login is valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("/users/register.html")


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    return render_template('users/alerts.html', alerts=user.get_alerts())


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Alert <small>for '{{ alert.item.name }}'</small></h1>
</div>
<p>Last price found <strong>{{ alert.item.price }}</strong></p>
<p>Last checked on <strong>{{ alert.last_checked.strftime('%d-%m-%Y at %H:%M') }}</strong></p>

<div class="card">
    <div class="card-body">
        <a class="btn btn-primary" href="{{ alert.item.url }}" role="button">Visit Site</a>
        <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit Alert</a>
        {% if alert.active %}
            <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate Alert</a>
        {% else %}
            <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate Alert</a>
            <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Permanently Delete Alert</a>
        {% endif %}
        <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check Alert Price</a>
    </div>
</div>
{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Edit Alert</h1>
    <hr>
</div>
<div class="form-size">
    <form method="post">
        <div class="form-group">
            <label for="name">Alert/Item Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder='{{ alert.name }}' value='{{ alert.name }}' disabled>
        </div>
        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="{{ alert.url }}" disabled>
        </div>
        <div class="form-group">
            <label for="price_limit">Alert limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="70.0" value='{{ alert.price_limit }}' aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">We'll send you an email when the price reaches or goes under this.</p>
            <button type="submit" class="btn btn-light">Update</button>
        </div>
    </form>
</div>
{% endblock %}

src/templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert</h1>
        <hr>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="70.0" aria-describedby="priceLimitBlock">
                <p id="priceLimitBlock" class="help-block">We'll send you an email when the price reaches or goes under this.</p>
                <button type="submit" class="btn btn-light">Create</button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Service</title>

    {% include 'html_dependencies.html' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/" title="Home">Pricing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('stores.index') }}">Stores</a>
                </li>
            </ul>
            {% if session['email'] %}
                <ul class="nav navbar-nav justify-content-end">
                    <li class="nav-item">
                        <a href="{{ url_for('users.user_alerts') }}" class="nav-link"><i class="fas fa-exclamation-triangle"></i> Your Alerts</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('users.logout_user') }}" class="nav-link"><i class="fas fa-sign-out-alt"></i> Log out</a>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav justify-content-end">
                    <li class="nav-item">
                        <a href="{{ url_for('users.register_user') }}" class="nav-link"><i class="fas fa-user-plus"></i> Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('users.login_user') }}" class="nav-link"><i class="fas fa-sign-in-alt"></i> Login</a>
                    </li>
                </ul>
            {% endif %}

        </div>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4"><strong>Pricing Service</strong></h1>
        <p class="lead"><strong>We scan online store websites to alert you of price drops in items that interest you.</strong></p>
        <p>Just sign up, and get started by adding the URL of an item that you wish to track. We'll do the rest!</p>
        <hr class="my-4">
        <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
    </div>
{% endblock %}

src/templates/html_dependencies.html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Store</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name" value="{{ store.name }}">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." value="{{ store.url_prefix }}" aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Search Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{{ store.query|tojson|safe }}' aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation marks!</span>
            </div>
            <button type="submit" class="btn btn-warning">Update</button>

        </form>
    </div>
{% endblock %}

src/templates/stores/new_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URLs of all items in this online store start with?</span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span" aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Search Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{"id": "price-now"}' aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation marks!</span>
            </div>
            <button type="submit" class="btn btn-light">Create</button>

        </form>
    </div>
{% endblock %}

src/templates/stores/store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <h1>Store
        <small>{{ store.name }}</small>
    </h1>
</div>
<p>All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
{% if session['email'] in config.ADMINS %}
<div class="card card-light">
    <div class="card-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
            Store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Permanently
            Delete Store</a>
    </div>
</div>
{% endif %}
{% endblock %}

src/templates/stores/store_index.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Stores <small>list of supported stores</small></h1>
    </div>
    <div class="list-group mt-3">
        {% for store in stores %}
        <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item list-group-item-action text-dark text-decoration-none">
            <h4 class="list-group-item-title">{{ store.name }}</h4>
            <p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p></a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
    <a class="btn btn-success mt-4" href="{{ url_for('stores.create_store') }}">
        <i class="fas fa-plus"></i> Create Store
    </a>
    {% endif %}
{% endblock %}

src/templates/stores/store_list.html
{% extends "base.html" %}
{% block content %}
    <p>Nothing here yet!</p>
{% endblock %}

src/templates/users/alerts.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h1>Alerts<small class="text-muted">&nbsp; &nbsp; showing already existing alerts</small></h1>
        <hr>
    </div>
    <div class="list-group mt-4">
        {% for alert in alerts %}
        <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item list-group-item-action p-3 mb-2 text-dark text-decoration-none {{ 'list-group-item-warning' if not alert.active else '' }}">
            <h4 class="list-group-title">
                {{ '<i class="fas fa-minus-circle"></i> '|safe if not alert.active else ''}} Alert for {{ alert.item.name }}</h4>
            <p class="list-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
                Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }}</strong></p>
        </a>
        {% endfor %}
    </div>
    <a class="btn btn-success mt-3" href="{{ url_for('alerts.create_alert') }}"><i class="fas fa-plus"></i> Create new</a>
{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
   <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Log in</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-success">Sign up</button>
        </form>
    </div>
{% endblock %}